[tool.poetry]
name = "sso_manager"
version = "0.1.0"
description = "A brief description of your project"
authors = ["Islam Elkadi <ielkadi@icloud.com>"]
packages = [
    { include = "src" }
]

[tool.poetry.dependencies]
python = "^3.13"
jsonschema = "4.22.0"
boto3 = "1.34.136"
PyYAML = "6.0.2"
typer = "0.15.1"
rich = "13.9.4"

[tool.poetry.group.dev.dependencies]
pre-commit = "3.6.0"
pyclean = "3.0.0"
moto = "5.0.11"
pytest = "8.1.1"
pytest-xdist = "3.6.1"
pytest-cov = "5.0.0"
pylint = "3.0.3"
black = "23.12.0"
shellcheck-py = "0.10.0.1"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v -ra -q -p no:warnings"
log_cli = true
log_cli_level = "INFO"
log_format = "%(asctime)s %(levelname)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
minversion = "6.0"
filterwarnings = "ignore"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"