[project]
version = "0.1.0"
name = "cloud_pass"
requires-python = ">=3.11"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 68", "wheel >= 0.41"]

[tool.setuptools.packages.find]
exclude = ["tests"]