AWSTemplateFormatVersion: 2010-09-09
Description: CFN Template to create cloudwatch logs

Parameters:

  # General params
  AppName:
    Type:        String
    Description: Environment name

  # KMS params
  CwlKmsKeyArn:
    Type:        AWS::SSM::Parameter::Value<String>
    Description: CloudWatch log KMS Key ID


Resources:

  ######################################
  #                 CWL                #
  ######################################

  AddRules:
    Type: AWS::Logs::LogGroup
    Properties:
      KmsKeyId:     !Ref CwlKmsKeyArn
      LogGroupName: !Sub /step-functions/${AppName}/add-rules

  ListGroups:
    Type: AWS::Logs::LogGroup
    Properties:
      KmsKeyId:     !Ref CwlKmsKeyArn
      LogGroupName: !Sub /step-functions/${AppName}/list-sso-groups

  ListPermissionSets:
    Type: AWS::Logs::LogGroup
    Properties:
      KmsKeyId:     !Ref CwlKmsKeyArn
      LogGroupName: !Sub /step-functions/${AppName}/list-permission-sets

  ######################################
  #                 SSM                #
  ######################################

  AddRulesArn:
    Type: AWS::SSM::Parameter
    Properties:
      Type:        String
      Name:        !Sub /cfn/${AppName}/cloudwatch/logroup/add-rules/arn
      Value:       !GetAtt AddRules.Arn
      Description: Add rules CloudWatch logs ARN

  ListGroupsArn:
    Type: AWS::SSM::Parameter
    Properties:
      Type:        String
      Name:        !Sub /cfn/${AppName}/cloudwatch/logroup/list-sso-groups/arn
      Value:       !GetAtt ListGroups.Arn
      Description: List SSO groups CloudWatch logs ARN

  ListPermissionSetsArn:
    Type: AWS::SSM::Parameter
    Properties:
      Type:        String
      Name:        !Sub /cfn/${AppName}/cloudwatch/logroup/list-permission-sets/arn
      Value:       !GetAtt ListPermissionSets.Arn
      Description: List permission sets CloudWatch logs ARN
