AWSTemplateFormatVersion: 2010-09-09
Description: CFN Template to create SSO Manager AWS application configuration

Parameters:

  AppName:
    Type:        String
    Description: Application's name
    Default:     sso-manager

  AppPrefix:
    Type:        String
    Description: Application's name prefix
    Default:     permia-id

Resources:

  Application:
    Type: AWS::AppConfig::Application
    Properties:
      Name:        !Sub ${AppPrefix}-${AppName}
      Description: !Sub ${AppPrefix}-${AppName} application
      Tags:
        - Key:   app-name
          Value: !Sub ${AppPrefix}-${AppName}