AWSTemplateFormatVersion: 2010-09-09
Description: CFN Template to create dynamodb tables
Parameters:
  # General params
  AppName:
    Type:        String
    Description: Application's name

  # Dynamodb params
  BillingMode:
    Type:        String
    Default:     PAY_PER_REQUEST
    Description: On demand billing mode

  HashKey:
    Type:        String
    Default:     pk
    Description: Dynamodb table hash key

  RangeKey:
    Type:        String
    Default:     sk
    Description: Dynamodb table range key

  DynamodbKmsId:
    Type:        AWS::SSM::Parameter::Value<String>
    Description: Dynamodb KMS key id

Resources:

  #########################################
  #                   DDB                 #
  #########################################

  CloudPassDataTable:
    Type: AWS::DynamoDB::Table
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W73
            reason: False alarm, billing mode included as ref variables
    Properties:
      BillingMode: !Ref BillingMode
      KeySchema:
        - AttributeName: !Ref HashKey
          KeyType:       HASH
        - AttributeName: !Ref RangeKey
          KeyType:       RANGE
      AttributeDefinitions:
        - AttributeName: !Ref HashKey
          AttributeType: S
        - AttributeName: !Ref RangeKey
          AttributeType: S
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled:     true
        SSEType:        KMS
        KMSMasterKeyId: !Ref DynamodbKmsId

  #########################################
  #                   SSM                 #
  #########################################

  CloudPassDataTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Type:       String
      Name:       !Sub /cfn/${AppName}/dynamodb/table/arn
      Value:      !GetAtt CloudPassDataTable.Arn
      Description: CloudPass data table ARN

  CloudPassDataTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Type:        String
      Name:        !Sub /cfn/${AppName}/dynamodb/table/name
      Value:       !Ref CloudPassDataTable
      Description: CloudPass data table name
