AWSTemplateFormatVersion: 2010-09-09
Description: CFN Template to create KMS Encryption Keys

Parameters:

  # CodeBuild params
  AppName:
    Type:        String
    Description: Application name

Resources:

  ######################################
  #                 Keys               #
  ######################################

  # CloudWatch
  CloudWatchLogsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS Key to access CloudWatch logs
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: CwlKmsPolicy
        Statement:
          - Sid: Enable key administration
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action:
              - kms:Create*
              - kms:Describe*
              - kms:Enable*
              - kms:List*
              - kms:Put*
              - kms:Update*
              - kms:Revoke*
              - kms:Disable*
              - kms:Get*
              - kms:Delete*
              - kms:TagResource
              - kms:UntagResource
              - kms:ScheduleKeyDeletion
              - kms:CancelKeyDeletion
            Resource: "*"
          - Sid: Enable key usage by cloudwatch logs
            Effect: Allow
            Principal:
              Service:
                - !Sub logs.${AWS::Region}.amazonaws.com
            Action:
              - kms:Encrypt*
              - kms:Decrypt*
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:Describe*
            Resource: "*"
            Condition:
              ArnLike:
                kms:EncryptionContext:aws:logs:arn: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:*

  # Dynamodb
  DynamodbKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS Key to access Dynamodb data store
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: DynamodbKmsPolicy
        Statement:
          - Sid: Enable key administration
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action:
              - kms:Create*
              - kms:Describe*
              - kms:Enable*
              - kms:List*
              - kms:Put*
              - kms:Update*
              - kms:Revoke*
              - kms:Disable*
              - kms:Get*
              - kms:Delete*
              - kms:ScheduleKeyDeletion
              - kms:CancelKeyDeletion
            Resource: "*"
          - Sid: Enable use of key
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - kms:DescribeKey
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey
              - kms:GenerateDataKeyWithoutPlaintext
            Resource: "*"
            Condition:
              StringEquals:
                kms:CallerAccount: !Ref AWS::AccountId

  ######################################
  #                 SSM                #
  ######################################

  # CloudWatch logs
  CloudWatchLogsKeyArnSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Type:        String
      Name:        !Sub /cfn/${AppName}/kms/logs/arn
      Value:       !GetAtt CloudWatchLogsKey.Arn
      Description: CloudWatch logs key arn

  CloudWatchLogsKeyIdSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Type:        String
      Name:        !Sub /cfn/${AppName}/kms/logs/id
      Value:       !Ref CloudWatchLogsKey
      Description: CloudWatch logs key ID

  # Dynamodb logs
  DynamodbKeyArnSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Type:        String
      Name:        !Sub /cfn/${AppName}/kms/dynamodb/arn
      Value:       !GetAtt DynamodbKey.Arn
      Description: Dynamo DB key arn

  DynamodbKeyIdSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Type:        String
      Name:        !Sub /cfn/${AppName}/kms/dynamodb/id
      Value:       !Ref DynamodbKey
      Description: Dynamo DB key ID
