AWSTemplateFormatVersion: 2010-09-09
Description: CFN Template to the SSO manager lambda

Parameters:

  # General params
  AppName:
    Type:        String
    Description: Application's name

  AppPrefix:
    Type:        String
    Description: Application's name prefix

  IsDryRun:
    Type:        String
    Description: Run the app in dry run mode or not

  # Identity Center & Organizations params
  RootOUId:
    Type:        String
    Description: AWS Organizations Root OU ID
    NoEcho:      true

  IdentityStoreId:
    Type:        String
    Description: AWS Identity Store ID
    NoEcho:      true

  IdentityStoreArn:
    Type:        String
    Description: AWS Identity Store ARN
    NoEcho:      true

  SsoManifetFileName:
    Type:        String
    Description: SSO Manifest file name
    Default:     sso_manifest.yaml

  # Lambda params
  LambdaMemorySize:
    Type: Number
    Default: 128
    MinValue: 128
    MaxValue: 512
    Description: Lambda function memory

  LambdaTimeout:
    Type: Number
    Default: 10
    Description: Lambda function timeout Timeout

  LambdaAlias:
    Type: String
    Default: live
    Description: Lambda function alias name

  LambdaRuntime:
    Type: String
    Default: python3.12
    Description: Lambda runtime

  # S3 params
  S3BucketName:
    Type:        AWS::SSM::Parameter::Value<String>
    Description: S3 Bucket Name

  S3BucketArn:
    Type:        AWS::SSM::Parameter::Value<String>
    Description: S3 Bucket ARN

  # KMS params
  CwlKmsArn:
    Type:        AWS::SSM::Parameter::Value<String>
    Description: CloudWatch logs KMS ARN

  S3KmsArn:
    Type:        AWS::SSM::Parameter::Value<String>
    Description: S3 Bucket KMS Key ARN

Resources:

  ######################################
  #                 IAM                #
  ######################################

  # Managed Policy
  SsoManagerManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: String
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: !Ref S3KmsArn
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource:
              - !Join [ / , [ !Ref S3KmsArn, "*" ] ]
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - !Ref S3KmsArn
          - Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource:
              - !Ref CwlKmsArn

  # IAM Roles
  SsoManagerLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: IAM role assumed by list business lambda
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref SsoManagerManagedPolicy
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  ######################################
  #                Lambda              #
  ######################################

  SsoManagerLambda:
    Type: AWS::Lambda::Function
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3002
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: No need to deploy to VPC
          - id: W92
            reason: No need to set reserved concurrency
    Properties:
      FunctionName: !Sub ${AppPrefix}-${AppName}
      Code:         ../../src/build/app
      Handler:      index.lambda_handler
      Role:         !GetAtt SsoManagerLambdaExecutionRole.Arn
      Runtime:      !Ref LambdaRuntime
      Timeout:      !Ref LambdaTimeout
      MemorySize:   !Ref LambdaMemorySize
      Environment:
        Variables:
          IS_DRY_RUN:                !Ref IsDryRun
          ROOT_OU_ID:                !Ref RootOUId
          IDENTITY_STORE_ID:         !Ref IdentityStoreId
          IDENTITY_STORE_ARN:        !Ref IdentityStoreArn
          MANIFEST_FILE_S3_LOCATION: !Sub S3://${S3BucketName}/${SsoManifetFileName}

  ######################################
  #           Version & Alias          #
  ######################################

  # Version & Alias
  SsoManagerLambdaVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref SsoManagerLambda

  SsoManagerLambdaAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref SsoManagerLambda
      FunctionVersion: !GetAtt SsoManagerLambdaVersion.Version
      Name: !Ref LambdaAlias

  ######################################
  #                 SSM                #
  ######################################

  SsoManagerLambdaArnSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Type:        String
      Name:        !Sub /${AppPrefix}/${AppName}/lambda/sso-manager/arn
      Value:       !GetAtt SsoManagerLambda.Arn
      Description: Sso Manager lambda function ARN

  SsoManagerLambdaNameSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Type:        String
      Name:        !Sub /${AppPrefix}/${AppName}/lambda/sso-manager/name
      Value:       !Ref SsoManagerLambda
      Description: Sso Manager lambda function name