AWSTemplateFormatVersion: 2010-09-09
Description: CFN Template to create and deploy the cfn & source code that powers the cloud pass security app

Parameters:

  # General params
  AppName:
    Type:        String
    Description: Application's name

Resources:

  ########################################
  #                Wave 1                #
  ########################################

  KMS:
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3002
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./kms.yaml
      Parameters:
        AppName: !Ref AppName

  ########################################
  #                Wave 2                #
  ########################################

  CWL:
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3002
    DependsOn:
      - KMS
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cwl.yaml
      Parameters:
        AppName:      !Ref AppName
        CwlKmsKeyArn: !Sub /cfn/${AppName}/kms/logs/arn

  DDB:
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3002
    DependsOn:
      - KMS
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ddb.yaml
      Parameters:
        AppName:       !Ref AppName
        DynamodbKmsId: !Sub /cfn/${AppName}/kms/dynamodb/id