AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for sso-groups

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:

  Function:
    Timeout:    3
    MemorySize: 128
    Tracing:    Active

  Api:
    TracingEnabled: true

Resources:
  SsoGroups:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: index.lambda_handler
      Runtime: python3.11
      Timeout: 60
      MemorySize: 128
      Layers:
        - !Ref layer
      Architectures:
        - x86_64
      Environment:
        Variables:
          IDENTITY_STORE_ID: d-9d677283e8

  layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ../../layers/python
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: SSO
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    DependsOn: ApplicationResourceGroup
    Properties:
      ResourceGroupName:        SSO
      AutoConfigurationEnabled: true

Outputs:

  SsoGroupsFunction:
    Description: SSO Groups Lambda Function ARN
    Value:       !GetAtt SsoGroups.Arn
