# General constants
MAX_RETRIES = 5
RETRY_DELAY_SECONDS = 2.0

# AWS service constants
OU_TARGET_TYPE_LABEL = "OU"
ACCOUNT_TARGET_TYPE_LABEL = "ACCOUNT"
USER_PRINCIPAL_TYPE_LABEL = "USER"
GROUP_PRINCIPAL_TYPE_LABEL = "GROUP"
PERMISSION_SET_TYPE_LABEL = "PERMISSION_SET"
SSO_ENTITLMENTS_APP_NAME = "sso_entitlements_manager"
