AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:

  Function:
    Timeout:    3
    MemorySize: 128
    Tracing:    Active

  Api:
    TracingEnabled: true

Resources:

  app:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: index.lambda_handler
      Runtime: python3.11
      Timeout: 60
      MemorySize: 128
      Layers:
        - !Ref layer
      Architectures:
        - x86_64
      Environment:
        Variables:
          HASH_KEY: id
          RANGE_KEY: record_id
          TABLE_NAME: cloud-pass-DDB-NTQQ162LUV44-CloudPassDataTable-14MI9RZRHD8TM

      Events:
        HealthCheck:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get

  layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ../../layers/python
      CompatibleRuntimes:
        - python3.11


  # ApplicationResourceGroup:
  #   Type: AWS::ResourceGroups::Group
  #   Properties:
  #     Name:
  #       Fn::Join:
  #       - ''
  #       - - ApplicationInsights-SAM-
  #         - Ref: AWS::StackName
  #     ResourceQuery:
  #       Type: CLOUDFORMATION_STACK_1_0

  # ApplicationInsightsMonitoring:
  #   Type: AWS::ApplicationInsights::Application
  #   Properties:
  #     ResourceGroupName:
  #       Fn::Join:
  #       - ''
  #       - - ApplicationInsights-SAM-
  #         - Ref: AWS::StackName
  #     AutoConfigurationEnabled: 'true'
  #   DependsOn: ApplicationResourceGroup
