AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:

  Function:
    Timeout:    3
    MemorySize: 128
    Tracing:    Active

  Api:
    TracingEnabled: true

Resources:

  app:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: index.lambda_handler
      Runtime: python3.12
      Timeout: 60
      MemorySize: 128
      Architectures:
        - x86_64
      Environment:
        Variables:
          POWERTOOLS_LOG_LEVEL: ERROR
          ROOT_OU_ID: r-tbu3
          DRY_RUN: False
          IDENTITY_STORE_ID: d-9d6761538c
          IDENTITY_STORE_ARN: arn:aws:sso:::instance/ssoins-882471b84caa6a5a
          MANIFEST_FILE_S3_LOCATION: s3://permia-id-sso-manager-026090521990/sso_manifest.yaml
