AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:

  Function:
    Timeout:    3
    MemorySize: 128
    Tracing:    Active

  Api:
    TracingEnabled: true

Resources:

  app:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: index.lambda_handler
      Runtime: python3.12
      Timeout: 60
      MemorySize: 128
      Architectures:
        - x86_64
