name: Linting

on:
  schedule:
    - cron: 0 3 * * *
  
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install .[dev]

      - name: Linting python code
        run:  make format

      - name: Linting CFN code
        uses: scottbrenner/cfn-lint-action@v2
        with:
          command: cfn-lint ./cfn/templates/*.yaml
