
name: Security Scanning

on:
  - push

permissions:
  actions: read
  contents: read
  security-events: write

jobs:

  security-scans:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: SAST - Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2