name: Testing

on:
  schedule:
      - cron: 0 3 * * *
  pull_request:

jobs:

  unit_testing:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Run unit tests
        run:  make unittest
